"""add modal_call_id to job

Revision ID: e2b0d5812415
Revises: 300d5d1bf4a9
Create Date: 2026-06-11 07:38:11.902265+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2b0d5812415'
down_revision: Union[str, None] = '300d5d1bf4a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('modal_call_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'modal_call_id')
    # ### end Alembic commands ###
