"""add outbox and retry_count

Revision ID: e5e9b8371bcd
Revises: e2b0d5812415
Create Date: 2026-06-11 09:23:18.046473+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5e9b8371bcd'
down_revision: Union[str, None] = 'e2b0d5812415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', name='outbox_status'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_outbox_processing', 'outbox_events', ['status', 'processing_started_at'], unique=False)
    op.create_index('idx_outbox_status_created', 'outbox_events', ['status', 'created_at'], unique=False)
    op.add_column('jobs', sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
    
    op.execute("""
    CREATE OR REPLACE FUNCTION notify_outbox_insert()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
        PERFORM pg_notify(
            'new_outbox_event',
            NEW.id::text
        );
        RETURN NEW;
    END;
    $$;
    """)
    op.execute("""
    CREATE TRIGGER outbox_notify_trigger
    AFTER INSERT ON outbox_events
    FOR EACH ROW
    EXECUTE FUNCTION notify_outbox_insert();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'retry_count')
    op.drop_index('idx_outbox_status_created', table_name='outbox_events')
    op.drop_index('idx_outbox_processing', table_name='outbox_events')
    op.execute("DROP TRIGGER IF EXISTS outbox_notify_trigger ON outbox_events;")
    op.execute("DROP FUNCTION IF EXISTS notify_outbox_insert();")
    
    op.drop_table('outbox_events')
    
    # Drop enum type manually
    op.execute("DROP TYPE outbox_status;")
    # ### end Alembic commands ###
