"""add client_ip to job

Revision ID: 300d5d1bf4a9
Revises: 001_initial
Create Date: 2026-06-11 07:23:43.191263+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '300d5d1bf4a9'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('client_ip', sa.String(length=45), nullable=True))
    op.alter_column('jobs', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique job identifier (UUIDv4).',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('jobs', 'status',
               existing_type=postgresql.ENUM('queued', 'downloading', 'rendering', 'completed', 'failed', name='job_status'),
               comment=None,
               existing_comment='Current lifecycle state of the render job.',
               existing_nullable=False,
               existing_server_default=sa.text("'queued'::job_status"))
    op.alter_column('jobs', 'progress',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               comment=None,
               existing_comment='Rendering progress percentage (0.0 - 100.0).')
    op.alter_column('jobs', 'replay_storage_key',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='Object storage key for the uploaded .osr replay file.',
               existing_nullable=False)
    op.alter_column('jobs', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Rendering configuration (skin, resolution, bg_dim, etc.).',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('jobs', 'beatmap_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='osu! beatmap ID resolved from the replay hash.',
               existing_nullable=True)
    op.alter_column('jobs', 'map_title',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='Human-readable beatmap title.',
               existing_nullable=True)
    op.alter_column('jobs', 'video_storage_key',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='Object storage key for the rendered .mp4 video.',
               existing_nullable=True)
    op.alter_column('jobs', 'thumb_storage_key',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='Object storage key for the generated thumbnail.',
               existing_nullable=True)
    op.alter_column('jobs', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Detailed error message if the job failed.',
               existing_nullable=True)
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment=None,
               existing_comment='Timestamp when the job was submitted.',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment=None,
               existing_comment='Timestamp of the last status update.',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_jobs_client_ip'), 'jobs', ['client_ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_client_ip'), table_name='jobs')
    op.alter_column('jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment='Timestamp of the last status update.',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment='Timestamp when the job was submitted.',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('jobs', 'error_message',
               existing_type=sa.TEXT(),
               comment='Detailed error message if the job failed.',
               existing_nullable=True)
    op.alter_column('jobs', 'thumb_storage_key',
               existing_type=sa.VARCHAR(length=512),
               comment='Object storage key for the generated thumbnail.',
               existing_nullable=True)
    op.alter_column('jobs', 'video_storage_key',
               existing_type=sa.VARCHAR(length=512),
               comment='Object storage key for the rendered .mp4 video.',
               existing_nullable=True)
    op.alter_column('jobs', 'map_title',
               existing_type=sa.VARCHAR(length=512),
               comment='Human-readable beatmap title.',
               existing_nullable=True)
    op.alter_column('jobs', 'beatmap_id',
               existing_type=sa.INTEGER(),
               comment='osu! beatmap ID resolved from the replay hash.',
               existing_nullable=True)
    op.alter_column('jobs', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Rendering configuration (skin, resolution, bg_dim, etc.).',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('jobs', 'replay_storage_key',
               existing_type=sa.VARCHAR(length=512),
               comment='Object storage key for the uploaded .osr replay file.',
               existing_nullable=False)
    op.alter_column('jobs', 'progress',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               comment='Rendering progress percentage (0.0 - 100.0).')
    op.alter_column('jobs', 'status',
               existing_type=postgresql.ENUM('queued', 'downloading', 'rendering', 'completed', 'failed', name='job_status'),
               comment='Current lifecycle state of the render job.',
               existing_nullable=False,
               existing_server_default=sa.text("'queued'::job_status"))
    op.alter_column('jobs', 'id',
               existing_type=sa.UUID(),
               comment='Unique job identifier (UUIDv4).',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_column('jobs', 'client_ip')
    # ### end Alembic commands ###
