"""add analytics_storage_key to jobs

Revision ID: fdd9222ab069
Revises: 055dabefef81
Create Date: 2026-06-17 06:22:19.597058+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdd9222ab069'
down_revision: Union[str, None] = '055dabefef81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('analytics_storage_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'analytics_storage_key')
    # ### end Alembic commands ###
